import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PortalNav from "../components/PortalNav";

import API_URL from "../config/api";

function DoctorDashboard() {
  const [referrals, setReferrals] = useState([]);
  const [loadError, setLoadError] = useState("");
  useEffect(() => { fetch(`${API_URL}/api/referrals`).then(async (response) => { const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Unable to load referrals."); setReferrals(result.data || []); }).catch((error) => setLoadError(error.message)); }, []);
  const active = referrals.filter((referral) => !["REJECTED", "COMPLETED", "ARRIVED"].includes(referral.status)).length;
  const pending = referrals.filter((referral) => ["CREATED", "SENT", "RECEIVED"].includes(referral.status)).length;
  const instant = referrals.filter((referral) => referral.urgency === "INSTANT").length;
  const completed = referrals.filter((referral) => ["COMPLETED", "ARRIVED"].includes(referral.status)).length;
  return <div className="sr-page"><PortalNav role="doctor" /><main className="sr-shell py-8 md:py-12"><section className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="sr-eyebrow">Clinical operations</p><h1 className="sr-title mt-3 text-4xl font-extrabold md:text-5xl">Doctor Command Center</h1><p className="mt-3 max-w-xl text-[#6f8198]">Coordinate referrals with a clear view of the patient queue, live hospital signals, and emergency pathways.</p></div><span className="sr-live">Network connected</span></section>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Active referrals" value={active} icon="↗" tone="blue" /><Kpi label="Pending review" value={pending} icon="◷" tone="amber" /><Kpi label="Instant referrals" value={instant} icon="!" tone="red" /><Kpi label="Completed transfers" value={completed} icon="✓" tone="green" /></section>

    {loadError && <p className="mt-6 rounded-2xl border border-[#f2c7ca] bg-[#fff1f2] p-4 text-sm font-bold text-[#b63d47]">{loadError}</p>}
    <section className="sr-card mt-8 overflow-hidden p-6 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="sr-eyebrow">Live clinical queue</p><h2 className="sr-title mt-2 text-2xl font-extrabold">Recent referrals</h2></div><Link to="/doctor/referrals" className="text-sm font-extrabold text-[#1769e0]">View all referrals →</Link></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-[#e7eff7] text-[10px] font-black uppercase tracking-[.14em] text-[#8aa0b7]"><tr><th className="px-3 py-3">Patient</th><th className="px-3 py-3">Required service</th><th className="px-3 py-3">Destination</th><th className="px-3 py-3">Mode</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Created</th></tr></thead><tbody>{referrals.slice(0, 8).map((referral) => <tr key={referral.id} className="border-b border-[#f0f5fa] text-sm"><td className="px-3 py-4 font-extrabold text-[#284664]">{referral.patientName}<span className="ml-2 text-xs font-normal text-[#9aabba]">#{referral.id}</span></td><td className="px-3 py-4 text-[#5f748b]">{referral.requiredService?.name || "Medical service"}</td><td className="px-3 py-4 text-[#5f748b]">{referral.destinationHospital?.name || "Pending"}</td><td className="px-3 py-4">{referral.urgency === "INSTANT" ? <span className="rounded-full bg-[#ffe8e8] px-3 py-1 text-[10px] font-black text-[#c83d4b]">EMERGENCY</span> : <span className="rounded-full bg-[#edf3f8] px-3 py-1 text-[10px] font-black text-[#60758a]">STANDARD</span>}</td><td className="px-3 py-4"><Status status={referral.status} /></td><td className="px-3 py-4 text-[#72869b]">{referral.createdAt ? new Date(referral.createdAt).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{!loadError && referrals.length === 0 && <p className="py-12 text-center text-sm text-[#72869b]">No referrals have been created yet.</p>}</div></section>
  </main></div>;
}
function Kpi({ label, value, icon, tone }) { const colors = { blue: "bg-[#eaf4ff] text-[#1769e0]", amber: "bg-[#fff5df] text-[#a96808]", red: "bg-[#ffe8e8] text-[#c83d4b]", green: "bg-[#e7f8f1] text-[#14845c]" }; return <div className="sr-kpi"><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl text-lg font-black ${colors[tone]}`}>{icon}</span><span className="sr-kpi-value">{value}</span></div><p className="mt-4 text-xs font-extrabold text-[#74889d]">{label}</p></div>; }
function Status({ status }) { const text = String(status || "PENDING").replaceAll("_", " "); const classes = status === "ACCEPTED" ? "bg-[#e7f8f1] text-[#14845c]" : status === "IN_TRANSIT" ? "bg-[#eaf4ff] text-[#1769e0]" : status === "COMPLETED" ? "bg-[#edf3f8] text-[#60758a]" : "bg-[#fff5df] text-[#a96808]"; return <span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${classes}`}>{text}</span>; }
export default DoctorDashboard;

