import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PortalNav from "../components/PortalNav";

function MedicalStaffProfile() {
  const [staff, setStaff] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("http://localhost:5000/api/medical-staff").then((response) => response.json()).then((result) => setStaff(result.data?.[0] || null)).catch(() => setError("Medical staff profile is unavailable.")); }, []);
  const profile = staff || { name: "Raj Kumar", role: "Paramedic", phone: "Not displayed", licenseNumber: "On file", ambulanceNumber: "AMB-101", isAvailable: true };
  return <div className="min-h-screen bg-slate-50"><PortalNav role="medical" /><main className="mx-auto max-w-5xl px-5 py-10 md:px-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">Transport team</p><h1 className="mt-3 text-4xl font-extrabold text-slate-900">Medical Staff Profile</h1><p className="mt-3 max-w-2xl text-slate-500">The profile used during ambulance coordination. Sensitive contact details are limited in this prototype.</p>{error && <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">{error}</p>}<section className="mt-8 rounded-3xl bg-white p-7 shadow-sm"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-100 text-2xl text-blue-700">+</div><h2 className="mt-5 text-2xl font-bold text-slate-900">{profile.name}</h2><p className="mt-1 text-slate-500">{profile.role} · {profile.ambulanceNumber || "Ambulance not assigned"}</p></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${profile.isAvailable ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>● {profile.isAvailable ? "Available" : "Unavailable"}</span></div><dl className="mt-8 grid gap-4 sm:grid-cols-3"><Info label="Phone" value={profile.phone || "Not displayed"} /><Info label="License" value={profile.licenseNumber || "Not applicable"} /><Info label="Current referral" value="Referral #12 · Assigned patient" /></dl><div className="mt-8 flex flex-wrap gap-3"><Link to="/medical-staff/consultation" className="rounded-full bg-blue-600 px-5 py-3 text-sm font-bold text-white">Consult Doctor</Link><Link to="/tracking?id=12" className="rounded-full border border-blue-200 px-5 py-3 text-sm font-bold text-blue-700">View Patient Tracking</Link></div></section></main></div>;
}
function Info({ label, value }) { return <div className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</dt><dd className="mt-2 text-sm font-bold text-slate-800">{value}</dd></div>; }
export default MedicalStaffProfile;
