import { useState } from "react";
import PortalNav from "../components/PortalNav";

const categories = ["All", "Lab Reports", "Imaging", "Prescriptions", "Consultation Notes", "Other"];

function PatientReports() {
  const [category, setCategory] = useState("All");
  const [selectedFile, setSelectedFile] = useState(null);
  return <div className="sr-page min-h-screen"><PortalNav role="patient" /><main className="sr-shell py-8 md:py-12"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="sr-eyebrow">Personal health records</p><h1 className="sr-title mt-3 text-4xl font-black md:text-5xl">Your medical reports.</h1><p className="mt-3 max-w-xl leading-7 text-[#6f8198]">Keep important documents ready for a future consultation or hospital handover.</p></div><span className="sr-mini-icon">▤</span></div><section className="sr-card sr-grid-glow mt-8 flex flex-col items-center justify-between gap-6 p-7 text-center md:flex-row md:text-left"><div className="flex items-center gap-5"><span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-3xl bg-[#eaf4ff] text-3xl text-[#1769e0]">▤</span><div><h2 className="text-xl font-black text-[#0c2c59]">Upload Medical Report</h2><p className="mt-1 text-sm text-[#6f8198]">PDF, JPG, JPEG or PNG · Prototype storage</p></div></div><label className="sr-btn-primary cursor-pointer"><span>Choose file</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" className="hidden" onChange={(event) => setSelectedFile(event.target.files?.[0] || null)} /></label></section>{selectedFile && <p className="mt-5 rounded-2xl border border-[#bcebd7] bg-[#effcf6] px-5 py-4 text-sm font-bold text-[#14845c]">{selectedFile.name} is ready to connect to report storage. No upload was sent.</p>}<div className="mt-8 flex gap-2 overflow-x-auto pb-2">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-black ${category === item ? "bg-[#1769e0] text-white" : "bg-white text-[#6f8198] shadow-sm"}`}>{item}</button>)}</div><section className="sr-card mt-4 p-8 text-center md:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-[#f5f9fd] text-3xl text-[#8aa0b7]">▤</div><h2 className="mt-5 text-xl font-black text-[#0c2c59]">No {category === "All" ? "medical reports" : category.toLowerCase()} connected yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#6f8198]">When storage is enabled, reports will appear here with their date, type, and file actions.</p></section></main></div>;
}
export default PatientReports;
