import { useEffect, useState } from "react";
import { io } from "socket.io-client";
import { Link } from "react-router-dom";
import PortalNav from "../components/PortalNav";

function PatientTeleconsultation() {
  const [doctors, setDoctors] = useState([]); const [selectedDoctor, setSelectedDoctor] = useState(null); const [consultation, setConsultation] = useState(null); const [notice, setNotice] = useState("");
  useEffect(() => { fetch("http://localhost:5000/api/coordination/doctors").then((response) => response.json()).then((result) => setDoctors(result.data || [])); const socket = io("http://localhost:5000"); socket.on("consultation-status-updated", setConsultation); return () => socket.disconnect(); }, []);
  async function startConsultation() { const response = await fetch("http://localhost:5000/api/coordination/consultations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ patientName: "Demo patient", doctorId: selectedDoctor.id, context: "Patient portal teleconsultation" }) }); const result = await response.json(); if (result.success) { setConsultation(result.data); setNotice("Consultation requested. This prototype does not place a real video call."); } }
  return <div className="min-h-screen bg-slate-50"><PortalNav role="patient" /><main className="mx-auto max-w-6xl px-5 py-10 md:px-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">Patient care</p><h1 className="mt-3 text-4xl font-extrabold text-slate-900">Live teleconsultation</h1><p className="mt-4 max-w-2xl text-slate-500">Choose a verified specialist and request a prototype consultation. Doctor availability and verification are backend demo data.</p><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-3xl bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Available specialists</p>{doctors.map((doctor) => <button type="button" key={doctor.id} onClick={() => setSelectedDoctor(doctor)} className={`mt-4 w-full rounded-2xl border p-5 text-left ${selectedDoctor?.id === doctor.id ? "border-blue-500 bg-blue-50" : "border-slate-100"}`}><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold text-slate-900">{doctor.name}</h2><p className="mt-1 text-sm text-slate-500">{doctor.specialization}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Verified · {doctor.isAvailable ? "Available" : "Busy"}</span></div><p className="mt-3 text-sm text-slate-500">{doctor.profile}</p></button>)}{selectedDoctor && <button type="button" onClick={startConsultation} className="mt-6 rounded-full bg-blue-600 px-5 py-3 text-sm font-bold text-white">Start Consultation</button>}</section><aside className="rounded-3xl bg-slate-900 p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-blue-200">Consultation room</p><div className="mt-6 flex aspect-video items-center justify-center rounded-2xl bg-slate-800 text-center"><div><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-blue-600 text-2xl">+</div><p className="mt-4 font-bold">{consultation ? "Consultation requested" : "Waiting for your consultation"}</p><p className="mt-2 text-sm text-slate-400">Prototype room. No live video stream is connected.</p></div></div><p className="mt-5 text-sm font-bold text-blue-100">Status: {consultation?.status || "NOT_STARTED"}</p>{notice && <p className="mt-3 text-sm text-emerald-300">{notice}</p>}<Link to="/patient" className="mt-6 inline-flex text-sm font-bold text-blue-200">Back to dashboard</Link></aside></div></main></div>;
}

export default PatientTeleconsultation;
